# -*- coding: utf-8 -*-
"""Translate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PZojjZR08P3U5tcY71706CCJnwn2Ufo8

Downloading Googletrans
"""

!pip install googletrans

"""Importing Translator"""

from googletrans import Translator
translator = Translator()

"""Making A list and translating them in hindi and adding in trans_list1"""

trans_list=['I went to the market yesterday.',
            'There I bought some vegetables and fruits.',
            'My friend also joined me on my way home.',
            'We had a good chat together.',
            'Best friends are very useful when one is alone']

trans_list_hi = []
for i in trans_list:
  a = translator.translate(i, dest='hi')
  trans_list_hi.append((a.text))
trans_list_hi

"""Spliting the Trans_list and making a new list name 'trans_list_split'"""

trans_list_split = []
for i in trans_list:
  trans_list_split.append(i.split())

trans_list_split

"""Translating the translate sentences again and adding them in trans_list2"""

trans_list_en = []
for j in trans_list_hi:
  b = translator.translate(j, dest='en')
  trans_list_en.append((b.text.split()))
trans_list_en

"""Calculating the score by BLEU"""

import nltk.translate
from nltk.translate.bleu_score import sentence_bleu
n=1
for i in range(0,len(trans_list_split)):
  reference = trans_list_split[i],trans_list_split[i]
  candidate = trans_list_en[i]
  score = sentence_bleu(reference, candidate, weights=(1,0,0,0))
  print(n,score)
  n= n+1